version: '3.2'
services:
  financials-ui:
    image: sbernhardtoc/financials-ui:latest
    #build: ./financials-ui
    networks:
      - financials-net
    ports:
      - "8088:80"
    links:
      - financials-ms
  financials-ms:
    image: sbernhardtoc/financials-ms-helidon:latest
    networks:
      - financials-net
    depends_on:
      - mongodb
    #  - kafka
    ports:
      - "7777:8080"
    #command: java -jar financials.jar
    links:
      - mongodb
      #- zipkin
  mongodb:
    image: mongo
    networks:
      - financials-net
    ports:
      - 27017:27017
networks:
    financials-net:
  #zookeeper:
  #  image: "confluent/zookeeper"
  #  ports:
  #    - 2181:2181
  #kafka:
  #  image: "confluent/kafka"
  #  ports:
  #    - 9092:9092
  #  environment:
  #    - KAFKA_ADVERTISED_HOST_NAME=kafka
  #    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #    - KAFKA_ADVERTISED_PORT=9092
  #    - KAFKA_CREATE_TOPICS=soaring-shippingnews
  #  depends_on:
  #    - zookeeper

  #zookeeper:
  #  image: wurstmeister/zookeeper
  #  ports:
  #    - "2181:2181"

  #kafka:
  #  build: infrastructure/kafka-docker
  #  depends_on:
  #    - zookeeper
  #  ports:
  #    - "9092:9092"
  #  environment:
  #    KAFKA_ADVERTISED_HOST_NAME: kafka
  #    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #    KAFKA_CREATE_TOPICS: "soaring-shippingnews:1:1"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock

  #storage:
  #  image: openzipkin/zipkin-cassandra
  #  container_name: cassandra
    # Uncomment to expose the storage port for testing
    # ports:
    #   - 9042:9042

  # Switch storage type to Cassandra
  #zipkin:
  #  image: openzipkin/zipkin
  #  environment:
  #    - STORAGE_TYPE=cassandra3
      # When using the test docker image, or have schema pre-installed, you don't need to re-install it
  #    - CASSANDRA_ENSURE_SCHEMA=false
      # When overriding this value, note the minimum supported version is 3.9
      # If you you cannot run 3.9+, but can run 2.2+, set STORAGE_TYPE=cassandra
  #    - CASSANDRA_CONTACT_POINTS=cassandra
  #  ports:
      # Port used for the Zipkin UI and HTTP Api
  #    - 9411:9411
  #  depends_on:
  #    - storage

  # Metrics configuration using Prometheus & Grafana
  #prometheus_srv:
  #  image: sbernhardtoc/prometheus
  #  container_name: prometheus_server
  #  hostname: prometheus_server
  #  ports:
  #    - 9090:9090

  #grafana:
  #  image: grafana/grafana
  #  container_name: grafana_server
  #  hostname: grafana_server
  #  ports:
  #    - 3000:3000
  #  depends_on:
  #    - prometheus_srv
