version: '2'
services:
  financials-ms:
    image: sbernhardtoc/financials-ms-1.0.0.0
    build: ./financials-ms
    depends_on:
      - financials-mongo-db
    ports:
      - "7777:8080"
    command: java -jar financials.jar
    links:
      - financials-mongo-db

  financials-mongo-db:
    image: mongo
    ports:
      - 27017:27017
