version: '2'
services:
  financials-ui:
    image: sbernhardtoc/financials-ms-ui:latest
    build: ./financials-ui
    ports:
      - "8088:80"
  financials-ms:
    image: sbernhardtoc/financials-ms:latest
    build: ./financials-ms
    depends_on:
      - mongodb
    ports:
      - "7777:8080"
    command: java -jar financials.jar
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
