# my global config
global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'financialsmicroservice'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['financials-ms-helidon.financials:8090']
