apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: financials-mongodb
spec:
  selector:
    app: financials-mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: financials-mongodb
        version: v1
    spec:
      containers:
      - image: mongo
        name: financials-mongodb
        ports:
        - containerPort: 27017
          hostPort: 27017
      restartPolicy: Always
