server:
  port: 8080
tracing:
  enabled: true
  service: "financial-microservice"
  protocol: "http"
  host: "zipkin.observability"
  port: 9411
  api-version: 2
  path: "/api/v2/spans"
app:
  db:
    host: "mongodb.financials"
    port: 27017
    name: "financials-db"
  kafka:
    bootstrap-servers: "130.61.35.61:9092"
    #bootstrap-servers: "10.10.0.137:9092,10.10.0.139:9092,10.10.0.140:9092"
    schema-registry-url: "http://130.61.35.61:8081/"
    kafka.acks: "all"
    retries: 0
    topic:
      paymentstatus: "soaring-paymentstatus"
      customerstatus: "soaring-customerstatus"
      ordercreated: "soaring-ordercreated"
      shippingnews: "soaring-shippingnews"
