# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: financials-ms
  name: financials-ms-dc
spec:
  selector:
    matchLabels:
      app: financials-ms
  replicas: 1
  template:
    metadata:
      labels:
        app: financials-ms
    spec:
      containers:
      - image: mongo
        name: financials-mongodb
        ports:
        - containerPort: 27017
          hostPort: 27017
      - image: sbernhardtoc/financials-ms:latest
        imagePullPolicy: Always
        name: financials-ms
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: financials-ms
  labels:
    app: financials-ms
spec:
  selector:
    app: financials-ms
  ports:
  - port: 7790
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    app: financials-ms
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: financials-ms-ingress
spec:
  rules:
  - host:
    http:
      paths:
      - path: /api/financials/*
        backend:
          serviceName: financials-ms
          servicePort: 7790
